# Generated by Django 5.0.6 on 2024-06-02 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='numbers_of_days',
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Hatchback', 'Hatchback')], default='Sedan', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
